name: libfaketime

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  main:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: make
        run: make
      - name: install
        run: sudo make install
      - name: configure
        run: |
          mkdir -p  ~/.libfaketime.d
          date -d 20200101 +%s > ~/.libfaketime.d/date.fake
      - name: smoke test
        run: env LD_PRELOAD=libfaketime.so.1 date -R
